version: '3.4'

services:
  amcart.productmodule.webapi:
    image: ${DOCKER_REGISTRY}amcartproductmodulewebapi
    build:
      context: .
      dockerfile: Modules\ProductModule\AmCart.ProductModule.WebAPI\Dockerfile

  amcart.ordermodule.webapi:
    image: ${DOCKER_REGISTRY}amcartordermodulewebapi
    build:
      context: .
      dockerfile: Modules\OrderModule\AmCart.OrderModule.WebAPI\Dockerfile

