runtime: aspnetcore
api_version: '1.0'
env: flexible
service: order
threadsafe: true
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 20
  cpu_utilization:
    target_utilization: 0.7
network: {}